<?php
if (!defined('ABSPATH')) exit;

// Template asset base used by the standalone onboarding shell.
$assets_url = plugin_dir_url(__FILE__) . 'assets/';
$assets_dir = plugin_dir_path(__FILE__) . 'assets/';
$onboarding_css = $assets_url . 'onboarding.css';
$onboarding_css_ver = file_exists($assets_dir . 'onboarding.css') ? (string) filemtime($assets_dir . 'onboarding.css') : null;

// Visual assets and static copy for the left marketing panel.
$left_bg = $assets_url . 'onboarding-left.webp';
$logo    = $assets_url . 'aeropro-logo.svg';
$logo2	 = $assets_url . 'aeropro-logo2.svg';
$left_title = 'A better way to prepare for the A&amp;P written exam.';
$left_subtitle = '';
$is_login_page = false;

// Login pages share this shell but need a body modifier for login-specific CSS.
global $post;
if ($post instanceof WP_Post) {
  $is_login_page = has_shortcode($post->post_content, 'vc_custom_login');
}

// Body classes scope the onboarding/login layout away from the active theme.
$body_classes = 'vc-onboarding';
if ($is_login_page) {
  $body_classes .= ' vc-onboarding--login';

  $login_action = isset($_GET['action']) ? sanitize_key(wp_unslash($_GET['action'])) : '';
  $login_checkemail = isset($_GET['checkemail']) ? sanitize_key(wp_unslash($_GET['checkemail'])) : '';

  if (in_array($login_action, ['rp', 'resetpass'], true)) {
    $body_classes .= ' vc-onboarding--login-set-password';
  } elseif ($login_action === 'reset_pass') {
    $body_classes .= ' vc-onboarding--login-forgot';
  } elseif ($login_checkemail === 'confirm') {
    $body_classes .= ' vc-onboarding--login-confirm';
  } else {
    $body_classes .= ' vc-onboarding--login-sign-in';
  }
} elseif ($post instanceof WP_Post) {
  $step_body_classes = [
    'register' => 'vc-onboarding--step-start',
    'registro-email' => 'vc-onboarding--step-password',
    'registro-datos' => 'vc-onboarding--step-profile',
    'verificar' => 'vc-onboarding--step-check-email',
    'registro-final' => 'vc-onboarding--step-final',
  ];

  if (isset($step_body_classes[$post->post_name])) {
    $body_classes .= ' ' . $step_body_classes[$post->post_name];
  }
}

// Stepper is rendered only for onboarding registration pages, never for login.
$onboarding_stepper_html = '';
if (!$is_login_page && $post instanceof WP_Post) {
  $stepper_current_step = [
    'registro-email' => 0,
    'registro-datos' => 1,
    'verificar' => 1,
  ][$post->post_name] ?? null;

  if ($stepper_current_step !== null) {
    $steps = [
      ['key' => 'account', 'label' => 'Account'],
      ['key' => 'profile', 'label' => 'Profile'],
    ];
    $current_step = $stepper_current_step;

    ob_start();
    include __DIR__ . '/steps/stepper.php';
    $onboarding_stepper_html = ob_get_clean();
  }
}

?><!doctype html>
<html <?php language_attributes(); ?>>
<head>
  <meta charset="<?php bloginfo('charset'); ?>">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <?php /* Poppins is loaded here so onboarding typography does not depend on the theme. */ ?>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap" rel="stylesheet">
  <?php /* Versioned CSS busts browser cache whenever onboarding.css changes. */ ?>
  <link rel="stylesheet" href="<?php echo esc_url(add_query_arg('ver', $onboarding_css_ver, $onboarding_css)); ?>" />
  <?php wp_head(); ?>
</head>

<body <?php body_class($body_classes); ?>>
  <?php /* Two-column shell: left visual panel plus right content card. */ ?>
  <div class="vc-onb-wrap<?php echo $is_login_page ? ' vc-onb-wrap--login' : ''; ?>">

    <?php /* Left panel: stable brand message and background image. */ ?>
    <aside class="vc-onb-left" style="background-image:url('<?php echo esc_url($left_bg); ?>')">
      <div class="vc-onb-left-content">
        <div>
          <h1 class="vc-onb-left-title"><?php echo $left_title; ?></h1>
          <?php if (!empty($left_subtitle)): ?>
            <p class="vc-onb-left-sub"><?php echo esc_html($left_subtitle); ?></p>
          <?php endif; ?>
        </div>
      </div>
    </aside>

    <?php /* Right panel: card host for shortcode content and optional stepper. */ ?>
    <main class="vc-onb-right">
      <div class="vc-onb-card">
      	<?php if (!empty($logo2)): ?>
          <img class="logo2" src="<?php echo esc_url($logo2); ?>" alt="Aeropro">
        <?php endif; ?>
        <?php if (!empty($onboarding_stepper_html)): ?>
          <?php /* Stepper markup is trusted because it is generated by the local template. */ ?>
          <div class="vc-onb-card__stepper">
            <?php echo $onboarding_stepper_html; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?>
          </div>
        <?php endif; ?>
        <div class="vc-onb-card__content">
          <?php /* WordPress page content renders the active shortcode step. */ ?>
          <?php
            while (have_posts()) : the_post();
              the_content();
            endwhile;
          ?>
        </div>
      </div>
    </main>

  </div>

  <?php wp_footer(); ?>
</body>
</html>
